name: Verovio music engraving library
markdown: kramdown
baseurl: "https://www.verovio.org"
exclude: []

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

tests-edit-path: "https://github.com/rism-digital/verovio.org/edit/gh-pages"
tests-verovio-edit-path: "https://editor.verovio.org/?file=https://raw.githubusercontent.com/rism-digital/verovio.org/gh-pages"

theme: verovio-theme

collections:
    tests:
        output: true